package com.mr.hibernate.entities;

// Generated 30 oct. 2014 01:30:28 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Authors generated by hbm2java
 */
public class Authors implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int AAuthorSk;
	private String AName;
	private String ACountry;
	private Set bookses = new HashSet(0);

	public Authors() {
	}

	public Authors(int AAuthorSk) {
		this.AAuthorSk = AAuthorSk;
	}

	public Authors(int AAuthorSk, String AName, String ACountry, Set bookses) {
		this.AAuthorSk = AAuthorSk;
		this.AName = AName;
		this.ACountry = ACountry;
		this.bookses = bookses;
	}

	public int getAAuthorSk() {
		return this.AAuthorSk;
	}

	public void setAAuthorSk(int AAuthorSk) {
		this.AAuthorSk = AAuthorSk;
	}

	public String getAName() {
		return this.AName;
	}

	public void setAName(String AName) {
		this.AName = AName;
	}

	public String getACountry() {
		return this.ACountry;
	}

	public void setACountry(String ACountry) {
		this.ACountry = ACountry;
	}

	public Set getBookses() {
		return this.bookses;
	}

	public void setBookses(Set bookses) {
		this.bookses = bookses;
	}

}
