package com.mr.hibernate.entities;

// Generated 30 oct. 2014 01:30:28 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Books generated by hbm2java
 */
public class Books implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int BBookSk;
	private Publishers publishers;
	private String BTitle;
	private Integer BPage;
	private Set authorses = new HashSet(0);

	public Books() {
	}

	public Books(int BBookSk) {
		this.BBookSk = BBookSk;
	}

	public Books(int BBookSk, Publishers publishers, String BTitle,
			Integer BPage, Set authorses) {
		this.BBookSk = BBookSk;
		this.publishers = publishers;
		this.BTitle = BTitle;
		this.BPage = BPage;
		this.authorses = authorses;
	}

	public int getBBookSk() {
		return this.BBookSk;
	}

	public void setBBookSk(int BBookSk) {
		this.BBookSk = BBookSk;
	}

	public Publishers getPublishers() {
		return this.publishers;
	}

	public void setPublishers(Publishers publishers) {
		this.publishers = publishers;
	}

	public String getBTitle() {
		return this.BTitle;
	}

	public void setBTitle(String BTitle) {
		this.BTitle = BTitle;
	}

	public Integer getBPage() {
		return this.BPage;
	}

	public void setBPage(Integer BPage) {
		this.BPage = BPage;
	}

	public Set getAuthorses() {
		return this.authorses;
	}

	public void setAuthorses(Set authorses) {
		this.authorses = authorses;
	}

}
