package com.mr.hibernate.entities;

// Generated 30 oct. 2014 01:30:28 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Publishers generated by hbm2java
 */
public class Publishers implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int PPublisherSk;
	private String PName;
	private Set bookses = new HashSet(0);

	public Publishers() {
	}

	public Publishers(int PPublisherSk) {
		this.PPublisherSk = PPublisherSk;
	}

	public Publishers(int PPublisherSk, String PName, Set bookses) {
		this.PPublisherSk = PPublisherSk;
		this.PName = PName;
		this.bookses = bookses;
	}

	public int getPPublisherSk() {
		return this.PPublisherSk;
	}

	public void setPPublisherSk(int PPublisherSk) {
		this.PPublisherSk = PPublisherSk;
	}

	public String getPName() {
		return this.PName;
	}

	public void setPName(String PName) {
		this.PName = PName;
	}

	public Set getBookses() {
		return this.bookses;
	}

	public void setBookses(Set bookses) {
		this.bookses = bookses;
	}

}
